<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQjxm5m4\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQjxm5m4/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerQjxm5m4.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerQjxm5m4\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerQjxm5m4\appProdProjectContainer([
    'container.build_hash' => 'Qjxm5m4',
    'container.build_id' => 'b5cfaf1c',
    'container.build_time' => 1600004879,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQjxm5m4');
